#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri
bundle exec rubocop -D --config .rubocop.yml
#!bundle exec script/validate-html I don't want errors, sorry!
gem build jekyll-theme-minimal.gemspec
